# DATASCI 350: group project random assignment

This notebook assigns students to groups of 4-5 for the final project.  
**Groups 01-07** were formed by students. **Groups 08-09** are randomly assigned.  
Random seed is `350` for reproducibility.

> **Note:** some emails were confirmed by students. All others follow
> the `firstname.lastname@emory.edu` pattern and **should be verified** against Canvas,
> as some students use middle names or different first names in their Emory email.

In [1]:
import random
import pandas as pd
from IPython.display import display, Markdown

# --- Known emails (confirmed by students) ---
known_emails = {
    "Minna Lai": "minna.lai@emory.edu",
    "Tianyi Zhou": "tianyi.grace.zhou@emory.edu",
    "Sarah Shao": "kexin.shao@emory.edu",
    "Serena Gu": "serena.gu@emory.edu",
    "Stan Xu": "stan.xu@emory.edu",
    "Yunshi Zhou": "yunshi.zhou@emory.edu",
    "Oliver Xie": "lxie46@emory.edu",
    "James Teng": "yteng27@emory.edu",
    "Bonnie Bao": "bonnie.bao@emory.edu",
}

def get_email(name):
    """Return known email or generate firstname.lastname@emory.edu."""
    if name in known_emails:
        return known_emails[name]
    return ".".join(name.lower().split()) + "@emory.edu"

# --- Pre-formed groups ---
group_01 = ["Minna Lai", "Sarah Shao", "Serena Gu", "Tianyi Zhou"]
group_02 = ["Christina Dai", "Eric Wang", "Joe Xia", "Kenneth He", "Tina Piltner"]
group_03 = ["Ayushi Chowksey", "Chau Anh Nguyen", "Hank Standaert", "Jacob Hillman", "Ryana Rajesh"]
group_04 = ["Bonnie Bao", "James Teng", "Oliver Xie", "Stan Xu", "Yunshi Zhou"]
group_05 = ["Eric Chen", "Steven Hu", "Yan Tian", "Yang Lyu"]
group_06 = ["Connor Lee", "Eshaan Dani", "Ihan Do", "Jonathan Luo", "Nikhil Makker"]
group_07 = ["Anny Huang", "Chrissy Wang", "Rola Ke", "Sissi Li", "Vicki Lin"]

pre_formed = [group_01, group_02, group_03, group_04, group_05, group_06, group_07]
pre_formed_names = {name for g in pre_formed for name in g}

# --- Full student roster (alphabetical) ---
# Excludes: Danilo Freire (teacher), Alix Morales (TA), Harris Wang (grader)
all_students = [
    "Anny Huang",
    "Arush Singhania",
    "Ayushi Chowksey",
    "Bonnie Bao",
    "Chau Anh Nguyen",
    "Christina Dai",
    "Chrissy Wang",
    "Connor Lee",
    "Eric Chen",
    "Eric Wang",
    "Eshaan Dani",
    "Fei Yi",
    "Hanna Florence",
    "Hank Standaert",
    "Ihan Do",
    "Jacob Hillman",
    "James Teng",
    "Joe Xia",
    "Jonathan Luo",
    "Kenneth He",
    "Lucas Huang",
    "Minna Lai",
    "Nikhil Makker",
    "Oliver Xie",
    "Rola Ke",
    "Ryana Rajesh",
    "Saahil Mardhekar",
    "Sarah Shao",
    "Selena Lin",
    "Serena Gu",
    "Sissi Li",
    "Stan Xu",
    "Steven Hu",
    "Theo Burns",
    "Tianyi Zhou",
    "Tina Piltner",
    "Vicente Martinez",
    "Vicki Lin",
    "Yan Tian",
    "Yang Lyu",
    "Yunshi Zhou",
    "Zhenyu Zou"
]

# --- Randomly assign remaining students ---
remaining = [s for s in all_students if s not in pre_formed_names]

random.seed(350)
shuffled = remaining.copy()
random.shuffle(shuffled)

# 9 remaining: 1 group of 5 + 1 group of 4 = 2 new groups
n_new_groups = 2
base_size = len(remaining) // n_new_groups      # 4
extra = len(remaining) % n_new_groups            # 1

new_groups = []
idx = 0
for i in range(n_new_groups):
    size = base_size + (1 if i < extra else 0)
    new_groups.append(shuffled[idx:idx + size])
    idx += size

# Combine all groups
all_groups = pre_formed + new_groups

print(f"Total students: {len(all_students)}")
print(f"Pre-formed: {len(pre_formed_names)} (Groups 01-07)")
print(f"Randomly assigned: {len(remaining)} (Groups 08-09)")
print(f"Total groups: {len(all_groups)}")

Total students: 42
Pre-formed: 33 (Groups 01-07)
Randomly assigned: 9 (Groups 08-09)
Total groups: 9

In [2]:
# Display all groups
n_pre = len(pre_formed)
for i, group in enumerate(all_groups, 1):
    label = "(self-formed)" if i <= n_pre else "(random)"
    display(Markdown(f"### Group {i:02d} {label}"))
    df = pd.DataFrame(
        [{"Name": s, "Email": get_email(s)} for s in sorted(group)]
    )
    df.index += 1
    display(df)

# Summary table
display(Markdown("---\n### Summary"))
rows = []
for i, group in enumerate(all_groups, 1):
    formed = "self-formed" if i <= n_pre else "random"
    for s in group:
        rows.append({"Group": f"{i:02d}", "Name": s, "Email": get_email(s), "Type": formed})
summary = pd.DataFrame(rows).sort_values("Name").reset_index(drop=True)
summary.index += 1
display(summary)

### Group 01 (self-formed)

          Name                        Email
1    Minna Lai          minna.lai@emory.edu
2   Sarah Shao         kexin.shao@emory.edu
3    Serena Gu          serena.gu@emory.edu
4  Tianyi Zhou  tianyi.grace.zhou@emory.edu

### Group 02 (self-formed)

            Name                    Email
1  Christina Dai  christina.dai@emory.edu
2      Eric Wang      eric.wang@emory.edu
3        Joe Xia        joe.xia@emory.edu
4     Kenneth He     kenneth.he@emory.edu
5   Tina Piltner   tina.piltner@emory.edu

### Group 03 (self-formed)

              Name                      Email
1  Ayushi Chowksey  ayushi.chowksey@emory.edu
2  Chau Anh Nguyen  chau.anh.nguyen@emory.edu
3   Hank Standaert   hank.standaert@emory.edu
4    Jacob Hillman    jacob.hillman@emory.edu
5     Ryana Rajesh     ryana.rajesh@emory.edu

### Group 04 (self-formed)

          Name                  Email
1   Bonnie Bao   bonnie.bao@emory.edu
2   James Teng      yteng27@emory.edu
3   Oliver Xie       lxie46@emory.edu
4      Stan Xu      stan.xu@emory.edu
5  Yunshi Zhou  yunshi.zhou@emory.edu

### Group 05 (self-formed)

        Name                Email
1  Eric Chen  eric.chen@emory.edu
2  Steven Hu  steven.hu@emory.edu
3   Yan Tian   yan.tian@emory.edu
4   Yang Lyu   yang.lyu@emory.edu

### Group 06 (self-formed)

            Name                    Email
1     Connor Lee     connor.lee@emory.edu
2    Eshaan Dani    eshaan.dani@emory.edu
3        Ihan Do        ihan.do@emory.edu
4   Jonathan Luo   jonathan.luo@emory.edu
5  Nikhil Makker  nikhil.makker@emory.edu

### Group 07 (self-formed)

           Name                   Email
1    Anny Huang    anny.huang@emory.edu
2  Chrissy Wang  chrissy.wang@emory.edu
3       Rola Ke       rola.ke@emory.edu
4      Sissi Li      sissi.li@emory.edu
5     Vicki Lin     vicki.lin@emory.edu

### Group 08 (random)

               Name                       Email
1   Arush Singhania   arush.singhania@emory.edu
2            Fei Yi            fei.yi@emory.edu
3  Saahil Mardhekar  saahil.mardhekar@emory.edu
4        Theo Burns        theo.burns@emory.edu
5  Vicente Martinez  vicente.martinez@emory.edu

### Group 09 (random)

             Name                     Email
1  Hanna Florence  hanna.florence@emory.edu
2     Lucas Huang     lucas.huang@emory.edu
3      Selena Lin      selena.lin@emory.edu
4      Zhenyu Zou      zhenyu.zou@emory.edu

---
### Summary

   Group              Name                        Email         Type
1     07        Anny Huang         anny.huang@emory.edu  self-formed
2     08   Arush Singhania    arush.singhania@emory.edu       random
3     03   Ayushi Chowksey    ayushi.chowksey@emory.edu  self-formed
4     04        Bonnie Bao         bonnie.bao@emory.edu  self-formed
5     03   Chau Anh Nguyen    chau.anh.nguyen@emory.edu  self-formed
6     07      Chrissy Wang       chrissy.wang@emory.edu  self-formed
7     02     Christina Dai      christina.dai@emory.edu  self-formed
8     06        Connor Lee         connor.lee@emory.edu  self-formed
9     05         Eric Chen          eric.chen@emory.edu  self-formed
10    02         Eric Wang          eric.wang@emory.edu  self-formed
11    06       Eshaan Dani        eshaan.dani@emory.edu  self-formed
12    08            Fei Yi             fei.yi@emory.edu       random
13    03    Hank Standaert     hank.standaert@emory.edu  self-formed
14    09    Hanna Florence     hanna.florence@emory.edu       random
15    06           Ihan Do            ihan.do@emory.edu  self-formed
16    03     Jacob Hillman      jacob.hillman@emory.edu  self-formed
17    04        James Teng            yteng27@emory.edu  self-formed
18    02           Joe Xia            joe.xia@emory.edu  self-formed
19    06      Jonathan Luo       jonathan.luo@emory.edu  self-formed
20    02        Kenneth He         kenneth.he@emory.edu  self-formed
21    09       Lucas Huang        lucas.huang@emory.edu       random
22    01         Minna Lai          minna.lai@emory.edu  self-formed
23    06     Nikhil Makker      nikhil.makker@emory.edu  self-formed
24    04        Oliver Xie             lxie46@emory.edu  self-formed
25    07           Rola Ke            rola.ke@emory.edu  self-formed
26    03      Ryana Rajesh       ryana.rajesh@emory.edu  self-formed
27    08  Saahil Mardhekar   saahil.mardhekar@emory.edu       random
28    01        Sarah Shao         kexin.shao@emory.edu  self-formed
29    09        Selena Lin         selena.lin@emory.edu       random
30    01         Serena Gu          serena.gu@emory.edu  self-formed
31    07          Sissi Li           sissi.li@emory.edu  self-formed
32    04           Stan Xu            stan.xu@emory.edu  self-formed
33    05         Steven Hu          steven.hu@emory.edu  self-formed
34    08        Theo Burns         theo.burns@emory.edu       random
35    01       Tianyi Zhou  tianyi.grace.zhou@emory.edu  self-formed
36    02      Tina Piltner       tina.piltner@emory.edu  self-formed
37    08  Vicente Martinez   vicente.martinez@emory.edu       random
38    07         Vicki Lin          vicki.lin@emory.edu  self-formed
39    05          Yan Tian           yan.tian@emory.edu  self-formed
40    05          Yang Lyu           yang.lyu@emory.edu  self-formed
41    04       Yunshi Zhou        yunshi.zhou@emory.edu  self-formed
42    09        Zhenyu Zou         zhenyu.zou@emory.edu       random